### ISSUE TITLE
2020-09 - main

### ISSUE THREAD

**Issue by ultrasound1372** [thunderdrop/IBMTTSDictionaries#11]
See readme for contributing guidelines. Any words you wish added, propose them here.

**Comment by ultrasound1372** [comment]
Due to lack of entries in this category, instead of duplicating a new issue with the same text and closing this one, I will rename this issue for the new month.

**Comment by ultrasound1372** [comment]
@amirsol81 I do not agree with the addition of "A" as an entry in ENUmain. What purpose does this serve? It just mangles some pronunciations for me.

**Comment by amirsol81** [comment]
@ultrasound1372 I mentioned the rationale for the inclusion of capital a 
in its commit: headlines containing capital a are read erroneously. Take 
these two, for instance:

Hero Rat Wins A Top Animal Award For Sniffing Out Landmines
Kim Jong Un Says He's Sorry That North Korean Troops Killed A South 
Korean Man


So may I know where this addition messes up with Eloquence? We can 
remove it if needed -- again as mentioned in the commit.

**Comment by ultrasound1372** [comment]
Since it's the 1st in UTC, I'm closing this to prepare the release and open new issues for next month.

**Comment by ultrasound1372** [comment]
@amirsol81 you can use this regex in your NVDA voice dictionary to make capital A be properly read if encountered in the context of a headline.
```
pattern: (\s+)A(\s+)
replacement: \1a\2
case sensitive checked
type Regular expression
```

**Comment by amirsol81** [comment]
@ultrasound1372 Thanks for the tip. I'll make use of it.

**Comment by ultrasound1372** [comment]
@amirsol81 actually, don't. There's a nasty flaw in that expression as it stands, it will lowercase the "A" at the beginning of a sentence, thus breaking punctuation parsing rules. A more suitable pattern might be the following.
```
([^.?!:;]\s+)A(\s+)
```
