### ISSUE TITLE
Pronunciation of Louis

### ISSUE THREAD

**Issue by jaybird110127** [thunderdrop/IBMTTSDictionaries#16]
Okay, this is almost certainly going to open up a huge can of worms. I understand why the word "Louis" is being pronounced like it is in the current community dictionary, especially since there's a rather well-known blind guy whose last name is Louis. However, he lives in the UK, where the way we're currently pronouncing Louis is correct. However, in the US, as far as I know, it is pronounced as "Loo iss." Using the UK pronunciation messes up US names, cities like St. Louis, etc. And yet, I know we're going to have someone from the UK say their way is right. I don't assume we can have separate entries for US and UK English, can we?

**Comment by amirsol81** [comment]
@jaybird110127 Thanks for bringing this up. Your point is well taken. "Louis", when altered, also tends to break "Joseph Louis", "Saint Louis", "Louis Farrakhan", etc. So I removed it as part of the latest commit just made to ENURoot.dic. The title of the commit is ENURoot: added 46 words, removed "Louis" and "financier".
For the sake of clarity, this particular dictionary is for American English and affects US English English Eloquence/IBMTTS voices, so it has to emphasize Americanisms over Britishisms. As such, if a dictionary project is developed for British English, "Louis" might be altered there more confidently.

**Comment by thunderdrop** [comment]
@amirsol81 You may wish to know that you can refer to issue numbers in your commit messages (e.g. Solves #16) and they'll be forever together.
