### ISSUE TITLE
Eloq ENU Dics - Jul 16.zip

### ISSUE THREAD

**Issue by amirsol81** [thunderdrop/IBMTTSDictionaries#3]
Added words to Root:
exscind -> `[.0Xk.1sInd]
ivanka -> `[.0X.1vaG.0kx]
metaxalone ->  `[.0mX.1tAk.0sx.2lon]
metatroph ->  `[.1mE.0Fx.2traf]
metatrophs ->  `[.1mE.0Fx.2trafs]
mephenoxalone ->  `[.2mE.0fX.1nak.0sx.2lon]
metestrus -> `[.0mE.1tE.0strxs]
metformin ->  `[.0mEt.1fcr.0mXn]
methedrine ->  `[.1mE.0TX.2drin]
methemoglobinemia ->  `[.2mE.2thi.0mx.2glo.0bX.1ni.0mi.0x]

Removed words from Root:
abjure
adjure

Notes:
1. Moved "Airbnb" from Root to Main for a natural pronunciation.
2. Added "AR", uppercase, to Main.
3. Added "GUI", uppercase, to Main.
4. I got sick and tired of hearing "Nevada Access" whenever I encountered "NVAccess", so I altered "NV" in Abbr.dic. I know that Abbr files aren't to be distributed, but thought I'd notify you. I also did the same thing to Co as it badly affected the pronunciation of something liked "Co-authored by ... = Company-authored by ..." Also SD-card = South Dakota-card.
[Eloq ENU Dics - Jul 16.zip](https://github.com/thunderdrop/IBMTTSDictionaries/files/4931094/Eloq.ENU.Dics.-.Jul.16.zip)

**Comment by amirsol81** [comment]
Forgot to mention that I added "thingie" as another spelling of "thingy" to Root. "Thingy" was corrected before, and many dictionaries display "thingie" as its second or alternative spelling

**Comment by thunderdrop** [comment]
Hi, Amir. It's odd that you can't make PRs. I believe you, I'm just confused about that!

I've been thinking about something that I was going to run past you privately, before getting some public opinion. As I couldn't find a way to reach you, I'll ask you here. If you're comfortable with Git or are willing to learn some basic repo management, would you like to be a collaborator on this project? It's not a status thing, I just realised that as the largest contributer, and the person with the most daily changes, it is going to become tedious for everyone (you included) if you have to do everything through PRs and issues. In the interests of streamlining our project, I personally would be very comfortable making you a collaborator so you could submit changes at-will, and we could discuss and go through them as necessary.

I'm not trying to diminish the contributions of others by suggesting this, but Out of all of us, you are by far the most active in your modifications of the dictionary, and it seemed silly not to offer. Especially as I agree with @ultrasound1372 regarding the huge number of comments on #1.

Thoughts welcome.

**Comment by thunderdrop** [comment]
As a collaborator, your responsibilities would be no more involved than they are now, it would just give you better access to the workflow, rather than having you try to put bricks in the wall by pushing them up a hill first!

**Comment by amirsol81** [comment]
> As a collaborator, your responsibilities would be no more involved than they are now, it would just give you better access to the workflow, rather than having you try to put bricks in the wall by pushing them up a hill first!

It would be my honor to be a project collaborator. So please do whatever you deem appropriate. Thanks for the beneficent offer.

**Comment by ultrasound1372** [comment]
Yep, go ahead. I have no idea why creating a pull request would be unavailable unless github is doing the thing that it's done with some countries. And who said abbr.dic files aren't to be distributed? The loading in add-ons is currently a bit broken I guess, but that doesn't mean we shouldn't have them for when it's not.

**Comment by ultrasound1372** [comment]
When he's added as a contributor, this should be closed.

**Comment by thunderdrop** [comment]
@amirsol81 Done, welcome to the team!

**Comment by amirsol81** [comment]
> Yep, go ahead. I have no idea why creating a pull request would be unavailable unless github is doing the thing that it's done with some countries. And who said abbr.dic files aren't to be distributed? The loading in add-ons is currently a bit broken I guess, but that doesn't mean we shouldn't have them for when it's not.

Thanks! Under issue 1 you said: "I'll look into not loading ABBR.dic, though do keep in mind that you have to have abbreviations turned on in the synth." I thought it means that Abbr.dic isn't to be distributed.

**Comment by amirsol81** [comment]
> @amirsol81 Done, welcome to the team!

Huge thanks!

**Comment by ultrasound1372** [comment]
> Thanks! Under issue 1 you said: "I'll look into not loading ABBR.dic, though do keep in mind that you have to have abbreviations turned on in the synth." I thought it means that Abbr.dic isn't to be distributed.

I was saying I would look into IBMTTS add-ons not being able to load it.

**Comment by ultrasound1372** [comment]
OK so you can basically just put your files in as they are on your end and commit.

**Comment by amirsol81** [comment]
Folks, is creating pull requests really complicated? The Create New Issue is still unavailable here, meaning I can't select it! Of course, it first says something about comparing branches and such. I used to think that I can simply select the button, type a description, and send my files via an attachment. Guess I should go learn it afresh <LOL>!

**Comment by amirsol81** [comment]
> OK so you can basically just put your files in as they are on your end and commit.

Hmm. First I select the Pull requests link, and then the New pull request link. But on the new page which opens, the Create pull request is unavailable or, as sighted folks like to call it, grayed. Should I do something more? Accept my apologies for this abecedarian approach <smile>!

**Comment by amirsol81** [comment]
Folks, in an attempt to resolve my Pull Request creation issue, I removed all of my forked repos -- including this one. So it seems that I've lost my Collabrator status! Anyhow, the issue persists. The New Pull Request page asks me to compare two branches instead of displaying the PR-creation form. Of course there's nothing to compare so the button to create the PR is disabled.

**Comment by ultrasound1372** [comment]
You have to compare branches to make a pull request, so you would compare across forks, then pick this repo as the base and your repo as the head and the same branch, then go from there.
