### ISSUE TITLE
Randomisation of Dictionary Contents

### ISSUE THREAD

**Issue by thunderdrop** [thunderdrop/IBMTTSDictionaries#7]
@amirsol81 I've noticed when you commit your changes, everything in the Root dictionary gets shuffled around. Is there a reason for this, and is it possible to stop it from occurring?

**Comment by amirsol81** [comment]
> @amirsol81 I've noticed when you commit your changes, everything in the Root dictionary gets shuffled around. Is there a reason for this, and is it possible to stop it from occurring?

Unfortunately it's beyond my control. Actually the app via which I compile my entries and corrections does that each time I close it to save the changes. The app is EloqTalk and if you're running the SAPI-4 version of Eloquence -- say with the K1000, it's located at C:\Program Files (x86)\Common Files\SpeechWorks\ETI-Eloquence 6.1\eloqtalk.exe. Apart from generating corrections based on the root word which allows me to correct the entries more easily, it allows me to listen to the original word and the so-called translated or corrected word.

**Comment by thunderdrop** [comment]
Could you do your corrections in EloqTalk and then write the file with another program? It makes tracking diffs harder because nothing is ever in the same place, I.E. Line numbers never truly correspond to anything. I appreciate that EloqTalk can make things easier, and I'd not want to interrupt your local workflow, as it's your choice. But you could save the file with something else.

**Comment by ultrasound1372** [comment]
I personally use elocutor and it's SPR output option or just regular speech to check and create root entries. Then I just paste them at the bottom of the file. The massive shuffling makes git really confused.

**Comment by amirsol81** [comment]
Well, if I do it with EloqTalk, it performs the saving process itself. 
So it's not feasible to avoid the randomization that way. May I know 
what elocutor is and how I can grab it? Is it different from EloqTalk? I 
want to really resolve the randomization issue.

**Comment by amirsol81** [comment]
> I personally use elocutor and it's SPR output option or just regular speech to check and create root entries. Then I just paste them at the bottom of the file. The massive shuffling makes git really confused.

May I know where I can grab elocutor? Is it different from EloqTalk? Guess I'm frantically randomizing the dictionary contents <LOL>!

**Comment by ultrasound1372** [comment]
Another way is if eloq talk lets you use any files as a dictionary set you can just cut any new changes you make out of the file into our project and any time you add new entries through eloq talk it will go in this empty file which you can then paste on the bottom. If you add entries in batch they would be random, but at least our workflow wouldn't be broken. Or you can use whatever you have that lets you just plug SPR's into eloquence. I thought elocutor came with that speech works bundle?

**Comment by amirsol81** [comment]
Well, it's doable but it would take more time to handle copies and 
pastes. Guess I should bite the bullet and execute it <smile>.

Elocutor doesn't come with my copy of SAPI-4 Eloquence -- EloqTalk does. 
So can I grab it from a URL or something?

**Comment by amirsol81** [comment]
It's hopefully resolved but I appreciate it if you could provide a way for me to grab Elocutor. It seems to have some advantages over EloqTalk.
Thanks.

**Comment by thunderdrop** [comment]
> It's hopefully resolved but I appreciate it if you could provide a way for me to grab Elocutor. It seems to have some advantages over EloqTalk.
> Thanks.

The reason we haven't done that yet is because we're not sure what the licensing is on Eloquter and we don't want to get in trouble with GitHub. Sorry for the confusion.

**Comment by amirsol81** [comment]
@thunderdrop I understand <smile>. So any chance of emailing it to me or providing a website URL?

**Comment by thunderdrop** [comment]
Not sure who distributes those tools anymore, I believe those are abandonware. You don't seem to have a public email address.
