### ISSUE TITLE
ENUmain. dic cant fix AT&T with NVDA but it works with SAPI-4 Eloquence

### ISSUE THREAD

**Issue by amirsol81** [thunderdrop/IBMTTSDictionaries#8]
In an attempt to fix AT&T, I added the following to ENUmain.dic:
AT&T `[.2e.2ti.0xn.1ti]
While it works with Eloquence SAPI-4/Kurzweil 1000, I can't get it to work with NVDA. I even altered NVDA's treatment of & "And" by sending it directly to the synthesizer via the Preferences->Punctuation/symbol pronunciation dialog but it just results in a different pronunciation not the intended one. So the "dash" rule apparently fails here. Any solutions or work-arounds?

**Comment by thunderdrop** [comment]
This is odd, the ECI documentation says that this is acceptable for an  input key in Main, but I can't get it to work either. Might be a problem with the driver itself? @ultrasound1372

**Comment by ultrasound1372** [comment]
Could also be NVDA's splitting expressions that it uses when capitals are involved, splitting and such. It's why backquote voice tags don't work by default even if you have the symbols passing through, the number gets broken. A good fix I think is to add a pronunciation entry for AT, Eh T, which would fix things like AT vendors, and AT&T in one fell swoop.
