### ISSUE TITLE
Will we have a Dictionary release today?

### ISSUE THREAD

**Issue by amirsol81** [thunderdrop/IBMTTSDictionaries#9]
Folks, as mentioned in the Read Me file, the dictionaries should be released on the first day of each month. As such, I want to know if the first release will be made available today. If so, I suggest that the Read Me file also describe what NVDA users should do in order to use hyphenated words in ENUmain.dic. A setting should be altered in NVDA's Punctuation/Symbol Pronunciation dialog.

**Comment by ultrasound1372** [comment]
Yes, a release will be made today, sorry, we were both doing other things. I'll manage this, and update readme as described.
